---
- name: am i running in a container
  stat:
    path: /.dockerinit
  register: imacontainer
  changed_when: False

- include: deploy_monitors.yml
  when: not mon_containerized_deployment

- include: start_monitor.yml
  when:
    not mon_containerized_deployment and
    not imacontainer

- name: get ceph monitor version
  shell: ceph daemon mon."{{ ansible_hostname }}" version | cut -d '"' -f 4 | cut -f 1,2 -d '.'
  changed_when: false
  failed_when: "'No such file or directory' in ceph_version.stderr"
  register: ceph_version
  when: not imacontainer

- include: ceph_keys.yml
  when:
    not mon_containerized_deployment and
    not imacontainer

- include: create_mds_filesystems.yml
  when:
    not mon_containerized_deployment and
    groups[mds_group_name] is defined

- include: secure_cluster.yml
  when:
    secure_cluster and
    not mon_containerized_deployment

- include: ./docker/main.yml
  when: mon_containerized_deployment
