---
- name: activate monitor with upstart for or after infernalis release
  file:
    path: /var/lib/ceph/mon/ceph-{{ ansible_hostname }}/{{ item }}
    state: touch
    owner: ceph
    group: ceph
    mode: 0600
  changed_when: false
  with_items:
    - done
    - upstart
  when:
    ansible_distribution == "Ubuntu" and
    is_ceph_infernalis

- name: activate monitor with upstart before infernalis release
  file:
    path: /var/lib/ceph/mon/ceph-{{ ansible_hostname }}/{{ item }}
    state: touch
    owner: root
    group: root
    mode: 0600
  changed_when: false
  with_items:
    - done
    - upstart
  when:
    ansible_distribution == "Ubuntu" and
    not is_ceph_infernalis

- name: start and add that the monitor service to the init sequence (ubuntu)
  service:
    name: ceph-mon
    state: started
    enabled: yes
    args: "id={{ ansible_hostname }}"
  when: ansible_distribution == "Ubuntu"

# NOTE (leseb): somehow the service ansible module is messing things up
# as a safety measure we run the raw command
- name: start and add that the monitor service to the init sequence
  command: service ceph start mon
  changed_when: false
  when:
    ansible_distribution != "Ubuntu" and
    not is_ceph_infernalis

- name: start and add that the monitor service to the init sequence (for or after infernalis)
  service:
      name: ceph-mon@{{ ansible_hostname }}
      state: started
      enabled: yes
  changed_when: false
  when:
    ansible_distribution != "Ubuntu" and
    is_ceph_infernalis

- name: collect admin and bootstrap keys
  command: ceph-create-keys --id {{ ansible_hostname }}
  changed_when: false
  failed_when:  false
